version: '3.8'

services:
  bedrock-app:
    build: .
    container_name: bedrock-python-app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_ACCESS_KEY_SECRET=${AWS_ACCESS_KEY_SECRET}
      - AWS_REGION=${AWS_REGION}
      - LLM_MODEL=${LLM_MODEL}
    env_file:
      - .env
